branches:
  except: 
    - rpi

language: generic
sudo: required
env: SWIFT_VERSION=4.0

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      git clone "https://github.com/warmcat/libwebsockets" || exit 3;
      pushd libwebsockets || exit 5;
      (cmake . && make && sudo make install) || exit 5;
      sudo ldconfig;
      popd
    fi;

script:
  - ./test.sh
