branches:
  except: 
    - rpi

language: generic
sudo: required
env: SWIFT_VERSION=5.2.4

matrix:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode11

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update && sudo apt-get install libwebsockets-dev zlib1g-dev;
    else
      brew install libwebsockets;
    fi;

script:
  - swift test
